import type { Tour } from '../types';
export const tours: Tour[] = [
  {
    boardType: 'HB - Завтрак, Ужин',
    checkinDt: '11.05.2023',
    city_from: 'Астана',
    country: 'Египет',
    currency: 'KZT',
    description:
      'Отель с ухоженной зеленой территорией. Уютные номера, приветливый персонал, разнообразное питание. Отель состоит из главного одноэтажного здания и отдельно стоящих двухэтажных зданий. Рекомендуется для спокойного экономичного отдыха.',
    hotelName: 'Falcon Hills 3*',
    href: 'https://manyhotels.ru/#!/hotel=falcon-hills',
    id: 'b26bff794c70deeca01750e816cebdb3',
    nights: 7,
    occupancy: {
      adultsCount: 2,
      childAges: [],
      childrenCount: 0,
    },
    operator: 'Tourvisor / Аврора-БГ',
    price: 556608,
    region: 'Хадаба',
    roomType: 'standard garden/pool room',
    thumbnail: 'https://static.tourvisor.ru/hotel_pics/main400/208.jpg',
  },
  {
    boardType: 'HB - Завтрак, Ужин',
    checkinDt: '11.05.2023',
    city_from: 'Астана',
    country: 'Египет',
    currency: 'KZT',
    description:
      'Расположен в самом центре Наама Бей, в нескольких минутах ходьбы от центральной прогулочной улицы с множеством кафе, баров и магазинов. Пляж находится в бухте, в 900 м от отеля. Рекомендуем для молодежного и бюджетного отдыха.',
    hotelName: 'Falcon Naama Star 3*',
    href: 'https://manyhotels.ru/#!/hotel=falcon-naama-star',
    id: '630acccc45759fd9c1249b752675004b',
    nights: 7,
    occupancy: {
      adultsCount: 2,
      childAges: [],
      childrenCount: 0,
    },
    operator: 'Tourvisor / Аврора-БГ',
    price: 556608,
    region: 'Наама Бей',
    roomType: 'standard',
    thumbnail: 'https://static.tourvisor.ru/hotel_pics/main400/210.jpg',
  },
  {
    boardType: 'HB - Завтрак, Ужин',
    checkinDt: '12.05.2023',
    city_from: 'Астана',
    country: 'Египет',
    currency: 'KZT',
    description:
      'Уютный отель с ухоженной территорией, утопающей в цветах и зелени на второй береговой линии в курортном городе Шарм-Эль-Шейх. Состоит из основного одноэтажного здания и комплекса двухэтажных корпусов. Рекомендуется для молодежного отдыха.',
    hotelName:
      'Verginia Sharm Resort & Aqua Park (Ех. Verginia Sharm, Sol Verginia) 4*',
    href: 'https://manyhotels.ru/#!/hotel=sol-verginia',
    id: '8c927d73a511f3858e15960c834a15b0',
    nights: 6,
    occupancy: {
      adultsCount: 2,
      childAges: [],
      childrenCount: 0,
    },
    operator: 'Tourvisor / Kompas (KZ)',
    price: 630336,
    region: 'Шарм',
    roomType: 'standard garden view',
    thumbnail: 'https://static.tourvisor.ru/hotel_pics/main400/447.jpg',
  },
  {
    boardType: 'AI - Все Включено',
    checkinDt: '11.05.2023',
    city_from: 'Астана',
    country: 'Египет',
    currency: 'KZT',
    description:
      'Отель находится в Шарм-Эль-Шейхе, в 4 км от аэропорта. К услугам гостей — открытые бассейны, ресторан, бар, СПА-центр. Номера оснащены кондиционером, телевизором, телефоном, в некоторых есть балкон. ',
    hotelName: 'Palma Di Sharm Hollywood Resort (Ex. Hostmark) 4*',
    href: 'https://manyhotels.ru/#!/hotel=hostmark-palma-di-sharm',
    id: '5617172562f97aa8c89698dbd16673c7',
    nights: 7,
    occupancy: {
      adultsCount: 2,
      childAges: [],
      childrenCount: 0,
    },
    operator: 'Tourvisor / Аврора-БГ',
    price: 585598,
    region: 'Шарм',
    roomType: 'standard',
    thumbnail: 'https://static.tourvisor.ru/hotel_pics/main400/75395.jpg',
  },
  {
    boardType: 'AI - Все Включено',
    checkinDt: '11.05.2023',
    city_from: 'Астана',
    country: 'Египет',
    currency: 'KZT',
    description:
      'Отель расположен на второй береговой линии в районе Ом Эль Сид Хилл, в самом центре набережной Il Mercato, на которой находятся магазины. Отель удален от пляжа, но на обширной территории размещены крытые и открытые бассейны, спа и оздоровительный центр. Для гостей — просторные стильные номера. ',
    hotelName: 'Il Mercato Hotel (Ex. Iberotel) 5*',
    href: 'https://manyhotels.ru/#!/hotel=iberotel-il-mercato',
    id: '69c304c2c5878efd6a3f964fe6cd9d06',
    nights: 7,
    occupancy: {
      adultsCount: 2,
      childAges: [],
      childrenCount: 0,
    },
    operator: 'Tourvisor / Аврора-БГ',
    price: 604776,
    region: 'Шарм',
    roomType: 'standard',
    thumbnail: 'https://static.tourvisor.ru/hotel_pics/main400/2904.jpg',
  },
  {
    boardType: 'AI - Все Включено',
    checkinDt: '11.05.2023',
    city_from: 'Астана',
    country: 'Египет',
    currency: 'KZT',
    description:
      'Уютный отель для экономичного и спокойного отдыха в нескольких минутах ходьбы от торгового центра Старого города. Песчаный пляж отеля расположен через дорогу. Для гостей — бассейн для детей и взрослых, ресторан, анимация.',
    hotelName: 'Turquoise Beach Hotel (Ex. Turquoise Swiss Inn) 3*',
    href: 'https://manyhotels.ru/#!/hotel=turquoise-beach-hotel',
    id: 'f3f085256bf9bc71b0b604242ddccea7',
    nights: 7,
    occupancy: {
      adultsCount: 2,
      childAges: [],
      childrenCount: 0,
    },
    operator: 'Tourvisor / Аврора-БГ',
    price: 619940,
    region: 'Хадаба',
    roomType: 'standard',
    thumbnail: 'https://static.tourvisor.ru/hotel_pics/main400/515.jpg',
  },
  {
    boardType: 'BB - Только завтрак',
    checkinDt: '14.05.2023',
    city_from: 'Астана',
    country: 'Египет',
    currency: 'KZT',
    description:
      'Отель в районе Старого города, представляет собой комплекс двухэтажных бунгало. В 600 м  от отеля коралловый пляж, который отлично подойдет для дайвинга и снорклинга.',
    hotelName: 'Coral Hills Resort 4*',
    href: 'https://manyhotels.ru/#!/hotel=coral-hills-resort',
    id: 'f6f5b329eb684993bc646f1b1e5e85aa',
    nights: 6,
    occupancy: {
      adultsCount: 2,
      childAges: [],
      childrenCount: 0,
    },
    operator: 'Tourvisor / TezTour',
    price: 617824,
    region: 'Хадаба',
    roomType: 'standard garden view',
    thumbnail: 'https://static.tourvisor.ru/hotel_pics/main400/162.jpg',
  },
  {
    boardType: 'Overnight(RO)',
    checkinDt: '09.05.2023',
    city_from: 'Астана',
    country: 'Турция',
    currency: 'KZT',
    description:
      'Отель расположен в городе Сиде, в 1,1 км от песчаного пляжа Кумкой. К услугам гостей ресторан, бесплатная частная парковка, сезонный открытый бассейн и бар. На территории обустроена детская игровая площадка.',
    hotelName: 'New Garden Apartment 3*',
    href: 'https://manyhotels.ru/#!/hotel=new-garden-apartment',
    id: 'c4abf865a4d9076303e1a49eba9b9ac5',
    nights: 7,
    occupancy: {
      adultsCount: 2,
      childAges: [],
      childrenCount: 0,
    },
    operator: 'Tourvisor',
    price: 530958,
    region: 'Сиде',
    roomType: 'standard',
    thumbnail: 'https://static.tourvisor.ru/hotel_pics/main400/76028.jpg',
  },
  {
    boardType: 'AI - Все Включено',
    checkinDt: '11.05.2023',
    city_from: 'Астана',
    country: 'Турция',
    currency: 'KZT',
    description:
      'Уютный отель в поселке Бельдиби с небольшой компактной территорией. Состоит из трех основных 4-этажных зданий. Из номеров открывается прекрасный панорамный вид на горы. В 100 м от отеля находится автобусная остановка. ',
    hotelName: 'Akasia Resort (Acacia) 3*',
    href: 'https://manyhotels.ru/#!/hotel=acacia-resort',
    id: '9b31cb6ac71f421d1386ade91f34fa8f',
    nights: 8,
    occupancy: {
      adultsCount: 2,
      childAges: [],
      childrenCount: 0,
    },
    operator: 'Tourvisor',
    price: 534072,
    region: 'Бельдиби',
    roomType: 'standard',
    thumbnail: 'https://static.tourvisor.ru/hotel_pics/main400/9357.jpg',
  },
  {
    boardType: 'BB - Только завтрак',
    checkinDt: '11.05.2023',
    city_from: 'Астана',
    country: 'Турция',
    currency: 'KZT',
    description:
      'Отель в пешей доступности от песчаного пляжа предлагает гостям комфортабельные номера, открытый бассейн для взрослых и детей, ресторан, 2 бара. По утрам в ресторане отеля подаются турецкие завтраки. Рекомендуется для экономичного отдыха.',
    hotelName: 'Kleopatra Smile Hotel 3*',
    href: 'https://manyhotels.ru/#!/hotel=kleopatra-smile-hotel',
    id: 'db5e73bbdbb24b8b24816bc05910b343',
    nights: 8,
    occupancy: {
      adultsCount: 2,
      childAges: [],
      childrenCount: 0,
    },
    operator: 'Tourvisor / TezTour',
    price: 552568,
    region: 'Алания',
    roomType: 'standard',
    thumbnail: 'https://static.tourvisor.ru/hotel_pics/main400/75706.jpg',
  },
];
